# Make sure to change the action name here (must be unique).
# Update the rest as needed.
name: 'simple-addition-action'
description: 'add two numbers and return results.'
branding: # Look at documentation for branding options/requirements. These are my favorites.
  icon: 'plus'
  color: 'green'
inputs:
  input-one:
    description: 'First number to add'
    required: true
    default: '0'
  input-two:
    description: 'Second number to add'
    required: true
    default: '0'
outputs:
  sum:
    description: 'Result of the addition'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.input-one }}
    - ${{ inputs.input-two }}
