name: 'string-concatenation-action'
description: 'Concatenates two input strings.'
branding:
  icon: 'merge'
  color: 'purple'
inputs:
  input1:
    description: 'First string to concatenate'
    required: true
    default: 'Hello'
  input2:
    description: 'Second string to concatenate'
    required: true
    default: 'World'
outputs:
  concatenated-result:
    description: 'The concatenated string result'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.input1 }}
    - ${{ inputs.input2 }}
